'use client';
import dynamic from 'next/dynamic';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { useEffect, useMemo, useState } from 'react';
import type { Result, UseCase } from '../lib/engine';
import { ExperienceChrome, Reveal } from './experience-chrome';

const EvidenceScene=dynamic(()=>import('./evidence-scene').then(m=>m.EvidenceScene),{ssr:false});
const presets:Record<string,UseCase>={
  'Knowledge assistant':{name:'Internal knowledge assistant',purpose:'Answer internal policy questions from approved enterprise documents.',vendor:'Internal / TBD',model:'Local RAG stack',annual_volume:18000,hours_saved_per_case:.08,implementation_cost_eur:32000,annual_run_cost_eur:9000,exit_plan:true,incident_process:true},
  'Customer chatbot':{name:'Customer support chatbot',purpose:'Chat directly with customers and answer product and support questions.',vendor:'EU AI SaaS vendor',model:'Hosted conversational model',chatbot_or_human_interaction:true,personal_data:true,annual_volume:60000,hours_saved_per_case:.05,contract_dpa:true,subprocessor_inventory:true,exit_plan:true,incident_process:true,dpia_or_privacy_review:true,model_card_or_system_card:true},
  'Hiring copilot':{name:'CV ranking copilot',purpose:'Rank employment applicants and recommend which candidates advance to interviews.',vendor:'External ATS AI',model:'Candidate scoring model',employment_decisions:true,personal_data:true,annual_volume:9000,hours_saved_per_case:.12,contract_dpa:true,subprocessor_inventory:true,model_card_or_system_card:true,incident_process:true,dpia_or_privacy_review:true},
  'Emotion detector':{name:'Employee emotion detector',purpose:'Infer employee emotions from workplace video and use signals for management decisions.',vendor:'External vision AI',model:'Emotion classifier',workplace_emotion_recognition:true,personal_data:true,special_category_data:true,annual_volume:30000,hours_saved_per_case:.02}
};
const bools:[keyof UseCase,string][]=[['personal_data','Personal data'],['special_category_data','Special-category data'],['employment_decisions','Employment decision/support'],['critical_infrastructure_safety','Critical-infrastructure safety'],['chatbot_or_human_interaction','Human-facing chatbot'],['synthetic_media_generation','Synthetic media'],['human_oversight','Human oversight'],['logging_enabled','Technical logging'],['evaluation_plan','Evaluation plan'],['incident_process','Incident process'],['dpia_or_privacy_review','Privacy/DPIA review'],['contract_dpa','DPA / contract evidence'],['subprocessor_inventory','Subprocessor inventory'],['exit_plan','Exit plan'],['ai_disclosure_ready','AI disclosure ready'],['synthetic_content_marking_ready','Synthetic-content marking'],['formal_risk_management_file','Risk-management file'],['legal_classification_review','Legal classification review'],['appeal_process','Appeal / contestability'],['access_control_evidence','Access-control evidence'],['data_minimisation_policy','Data minimisation policy']];
const pipeline=['AI request','risk screen','vendor evidence','control gaps','approval route','value case','registry'];

function money(v:number){return new Intl.NumberFormat('en-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v)}
export function CommandCenter(){
 const reduced=useReducedMotion();
 const [active,setActive]=useState('Customer chatbot'); const [form,setForm]=useState<UseCase>(presets[active]); const [result,setResult]=useState<Result|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [history,setHistory]=useState<{name:string;risk:string;readiness:number}[]>([]); const [evaluation,setEvaluation]=useState<{cases:number;risk_band_accuracy:number;decision_accuracy:number}|null>(null);
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem('aigate-history')||'[]'))}catch{setHistory([])};fetch('/api/evaluation').then(r=>r.ok?r.json():null).then(x=>x&&setEvaluation(x)).catch(()=>{})},[]);
 useEffect(()=>{setForm(presets[active]);setResult(null);setError('')},[active]);
 const set=<K extends keyof UseCase>(k:K,v:UseCase[K])=>{setForm(f=>({...f,[k]:v}));setResult(null)};
 async function run(){setBusy(true);setError('');try{const r=await fetch('/api/screen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Screening failed');setResult(data);const next=[{name:form.name,risk:data.risk_band,readiness:data.readiness_score},...history].slice(0,5);setHistory(next);localStorage.setItem('aigate-history',JSON.stringify(next));}catch(e){setError(e instanceof Error?e.message:'Screening failed')}finally{setBusy(false)}}
 function downloadPack(){if(!result)return;const pack={generated_at:new Date().toISOString(),use_case:form,screening:result,scope:'portfolio decision-support; not legal advice'};const blob=new Blob([JSON.stringify(pack,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`aigate-${form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'screening'}.json`;a.click();URL.revokeObjectURL(url)}
 async function copySummary(){if(!result)return;await navigator.clipboard?.writeText(`${form.name} — ${result.risk_band} — ${result.decision} — readiness ${result.readiness_score}/100. ${result.ai_summary}`)}
 const color=useMemo(()=>result?.risk_band==='prohibited-review'?'danger':result?.risk_band==='high-risk-candidate'?'warn':result?.risk_band==='transparency'?'violet':'safe',[result]);
 return <main className="experience">
  <ExperienceChrome/>
  <nav className="nav glass"><a href="#top" className="brand"><span className="brand-mark">A</span>AIGATE<span>EU</span></a><div><a href="#screen">Screen</a><a href="#evidence">Evidence</a><a href="#value">Value</a><a href="#method">Method</a></div><span className="zero"><i/>zero-key public mode</span></nav>

  <section id="top" className="hero section stage">
   <motion.div className="hero-copy" initial={reduced?false:{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.85,ease:[.22,1,.36,1]}}>
    <p className="eyebrow"><span className="live-dot"/> AI procurement · governance · value control plane</p>
    <h1><span>Move AI from request</span><br/><em>to governed release.</em></h1>
    <p className="lede">AIGate turns an AI idea into a traceable decision: risk screening, vendor evidence, control gaps, approval routing and quantified value — with deterministic policy owning the gate.</p>
    <div className="hero-actions"><motion.a whileHover={reduced?undefined:{y:-2,scale:1.01}} className="primary" href="#screen">Run a screening <b>↗</b></motion.a><a className="secondary" href="#method">See the control model</a></div>
    <div className="proof"><span>no paid API</span><span>policy-first</span><span>evidence graph</span><span>synthetic portfolio data</span></div>
   </motion.div>
   <motion.div className="hero-scene" initial={reduced?false:{opacity:0,scale:.96,y:24}} animate={{opacity:1,scale:1,y:0}} transition={{duration:1,delay:.12,ease:[.22,1,.36,1]}}><EvidenceScene risk={result?.risk_band}/><div className="scene-status glass"><span><i className="pulse"/> deterministic engine</span><b>{result?result.risk_band:'awaiting screening'}</b></div></motion.div>
  </section>

  <div className="ticker" aria-hidden="true"><div>{[...pipeline,...pipeline].map((x,i)=><span key={`${x}-${i}`}>{x}<i>◆</i></span>)}</div></div>

  <Reveal className="metrics section stage"><div><b>4</b><span>screening bands</span></div><div><b>{evaluation?.cases??32}</b><span>synthetic evaluation cases</span></div><div><b>{evaluation?`${Math.round(evaluation.decision_accuracy*100)}%`:'100%'}</b><span>decision regression accuracy</span></div><div><b>2</b><span>policy implementations checked for parity</span></div></Reveal>

  <section id="screen" className="section stage"><Reveal className="section-head"><p className="eyebrow">01 · intake and decisioning</p><h2>Screen the use case<br/><em>before the purchase order.</em></h2><p className="section-copy">Move from a business idea to a structured, auditable intake. Every toggle changes the control context; every value input changes the economics.</p></Reveal><Reveal delay={.08} className="workspace"><aside className="panel glass presets"><div className="panel-kicker">Scenario library</div><h3>Choose a starting point</h3>{Object.keys(presets).map(p=><motion.button whileHover={reduced?undefined:{x:4}} className={active===p?'active':''} key={p} onClick={()=>setActive(p)}><span>{p}</span><i>→</i></motion.button>)}<hr/><label>Name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Purpose<textarea value={form.purpose} onChange={e=>set('purpose',e.target.value)}/></label><label>Vendor<input value={form.vendor||''} onChange={e=>set('vendor',e.target.value)}/></label><label>Model<input value={form.model||''} onChange={e=>set('model',e.target.value)}/></label></aside><div className="panel glass controls"><div className="panel-kicker">Control surface</div><h3>Context & evidence</h3><div className="toggle-grid">{bools.map(([k,l])=><label className="toggle" key={String(k)}><input type="checkbox" checked={Boolean(form[k]??(['human_oversight','logging_enabled','evaluation_plan'].includes(String(k))))} onChange={e=>set(k,e.target.checked as never)}/><span><i/>{l}</span></label>)}</div><div className="slider-grid"><label>Annual volume <b>{Number(form.annual_volume||0).toLocaleString()}</b><input type="range" min="1000" max="100000" step="1000" value={form.annual_volume||10000} onChange={e=>set('annual_volume',Number(e.target.value))}/></label><label>Minutes saved / case <b>{Math.round(Number(form.hours_saved_per_case||0)*60)}</b><input type="range" min="0" max="0.5" step="0.01" value={form.hours_saved_per_case||.05} onChange={e=>set('hours_saved_per_case',Number(e.target.value))}/></label><label>Implementation € <b>{money(Number(form.implementation_cost_eur||0))}</b><input type="range" min="0" max="120000" step="5000" value={form.implementation_cost_eur||25000} onChange={e=>set('implementation_cost_eur',Number(e.target.value))}/></label></div><motion.button whileTap={{scale:.99}} whileHover={reduced?undefined:{y:-2}} className="run" onClick={run} disabled={busy}>{busy?<><i className="spinner"/> Screening control path…</>:<>Run deterministic screening <span>→</span></>}</motion.button>{error&&<p className="error">{error}</p>}</div></Reveal></section>

  <section id="evidence" className="section result-section stage"><Reveal className="section-head"><p className="eyebrow">02 · evidence and release decision</p><h2>The decision is visible.<br/><em>So is the evidence behind it.</em></h2></Reveal><AnimatePresence mode="wait">{result?<motion.div key={result.decision} initial={{opacity:0,y:24,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-12}} transition={{duration:.5,ease:[.22,1,.36,1]}} className={`result-grid ${color}`}><div className="result-hero glass"><p className="eyebrow">decision</p><h2>{result.decision.replaceAll('_',' ')}</h2><div className="risk-pill"><i/>{result.risk_band}</div><p>{result.ai_summary}</p><div className="result-actions"><button onClick={downloadPack}>Download evidence pack</button><button onClick={copySummary}>Copy decision summary</button></div><small>{result.legal_notice}</small></div><div className="score glass"><span>readiness</span><strong>{result.readiness_score}</strong><div className="meter"><motion.i initial={{width:0}} animate={{width:`${result.readiness_score}%`}} transition={{duration:.8,ease:[.22,1,.36,1]}}/></div><span>evidence {result.evidence_score}% · vendor {result.vendor_score}%</span></div><div className="glass list"><h3>Why</h3>{result.reasons.map(x=><p key={x}>→ {x}</p>)}</div><div className="glass list"><h3>Missing evidence</h3>{(result.missing_controls.length?result.missing_controls:['No critical gaps detected']).slice(0,7).map(x=><p key={x}>○ {x}</p>)}</div><div className="glass route"><h3>Approval route</h3>{result.approval_route.map((x,i)=><motion.div initial={reduced?false:{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:i*.06}} key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</motion.div>)}</div><div className="glass list"><h3>Required controls</h3>{result.required_controls.slice(0,8).map(x=><p key={x}>✓ {x}</p>)}</div></motion.div>:<Reveal className="empty glass"><div className="empty-orbit"><i/><i/><i/></div><p className="eyebrow">waiting for a screening</p><h2>Reveal the control path.</h2><p>The result will show classification, decision, control gaps, evidence score, approval route and value case.</p><a href="#screen">Go to intake ↑</a></Reveal>}</AnimatePresence></section>

  <section id="value" className="section stage"><Reveal className="section-head"><p className="eyebrow">03 · value case</p><h2>Governance without a business case<br/><em>is just paperwork.</em></h2><p className="section-copy">The same use-case intake that drives risk also drives economics, so teams can compare control effort with operational value.</p></Reveal><div className="value-grid">{result?[['Annual benefit',money(result.annual_benefit_eur)],['Annual net value',money(result.annual_net_value_eur)],['First-year ROI',`${result.roi_pct}%`],['Payback',result.payback_months===null?'No payback':`${result.payback_months} months`]].map(([a,b],i)=><motion.div className="glass" key={a} initial={reduced?false:{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}} whileHover={reduced?undefined:{y:-4}}><span>{a}</span><b>{b}</b><i className="value-line"/></motion.div>):<Reveal className="glass value-placeholder">Value metrics appear after screening.</Reveal>}</div></section>

  <section id="method" className="section method stage"><Reveal className="section-head"><p className="eyebrow">04 · architecture</p><h2>Reasoning can advise.<br/><em>Policy owns authority.</em></h2></Reveal><Reveal delay={.08} className="flow"><div><small>01</small>AI request</div><i>→</i><div><small>02</small>deterministic screening</div><i>→</i><div><small>03</small>control gaps</div><i>→</i><div><small>04</small>approval route</div><i>→</i><div><small>05</small>registry & monitoring</div></Reveal><div className="method-grid"><Reveal className="glass"><span className="card-index">01</span><h3>Deterministic control plane</h3><p>Risk-band screening, approval routing, evidence scoring, vendor scoring and release decisioning are testable policy functions.</p></Reveal><Reveal delay={.08} className="glass"><span className="card-index">02</span><h3>Optional AI layer</h3><p>A local OpenAI-compatible model may explain evidence or summarize documents, but it cannot change a policy decision or authorize release.</p></Reveal><Reveal delay={.16} className="glass"><span className="card-index">03</span><h3>Commercial path</h3><p>Community mode stays zero-key. A future SaaS layer can add multi-tenancy, Postgres, SSO, connectors, evidence exports and EU-region operations.</p></Reveal></div></section>

  {history.length>0&&<section className="section stage"><Reveal className="section-head"><p className="eyebrow">local browser history</p><h2>Recent screenings</h2></Reveal><div className="history">{history.map((h,i)=><motion.div className="glass" whileHover={reduced?undefined:{y:-3}} key={`${h.name}-${i}`}><b>{h.name}</b><span>{h.risk}</span><strong>{h.readiness}/100</strong></motion.div>)}</div></section>}

  <section className="section closing stage"><Reveal><p className="eyebrow">open-source portfolio build</p><h2>Govern AI like a product,<br/><em>not a spreadsheet.</em></h2><p>Inspect the code, run the synthetic scenarios, or use the public control plane locally without a paid model API.</p><div className="hero-actions"><a className="primary" href="https://github.com/Samadritaacharya/aigate-ai-procurement-governance" target="_blank" rel="noreferrer">View source on GitHub ↗</a><a className="secondary" href="#top">Back to top ↑</a></div></Reveal></section>
  <footer className="section"><b>AIGate</b><span>AI Procurement, Governance & Value Control Plane</span><small>Portfolio-safe decision support · not legal advice</small></footer>
 </main>
}
