'use client';
import dynamic from 'next/dynamic';
import { AnimatePresence, motion } from 'motion/react';
import { useEffect, useMemo, useState } from 'react';
import type { Result, UseCase } from '../lib/engine';

const EvidenceScene=dynamic(()=>import('./evidence-scene').then(m=>m.EvidenceScene),{ssr:false});
const presets:Record<string,UseCase>={
  'Knowledge assistant':{name:'Internal knowledge assistant',purpose:'Answer internal policy questions from approved enterprise documents.',vendor:'Internal / TBD',model:'Local RAG stack',annual_volume:18000,hours_saved_per_case:.08,implementation_cost_eur:32000,annual_run_cost_eur:9000,exit_plan:true,incident_process:true},
  'Customer chatbot':{name:'Customer support chatbot',purpose:'Chat directly with customers and answer product and support questions.',vendor:'EU AI SaaS vendor',model:'Hosted conversational model',chatbot_or_human_interaction:true,personal_data:true,annual_volume:60000,hours_saved_per_case:.05,contract_dpa:true,subprocessor_inventory:true,exit_plan:true,incident_process:true,dpia_or_privacy_review:true,model_card_or_system_card:true},
  'Hiring copilot':{name:'CV ranking copilot',purpose:'Rank employment applicants and recommend which candidates advance to interviews.',vendor:'External ATS AI',model:'Candidate scoring model',employment_decisions:true,personal_data:true,annual_volume:9000,hours_saved_per_case:.12,contract_dpa:true,subprocessor_inventory:true,model_card_or_system_card:true,incident_process:true,dpia_or_privacy_review:true},
  'Emotion detector':{name:'Employee emotion detector',purpose:'Infer employee emotions from workplace video and use signals for management decisions.',vendor:'External vision AI',model:'Emotion classifier',workplace_emotion_recognition:true,personal_data:true,special_category_data:true,annual_volume:30000,hours_saved_per_case:.02}
};
const bools:[keyof UseCase,string][]=[['personal_data','Personal data'],['special_category_data','Special-category data'],['employment_decisions','Employment decision/support'],['critical_infrastructure_safety','Critical-infrastructure safety'],['chatbot_or_human_interaction','Human-facing chatbot'],['synthetic_media_generation','Synthetic media'],['human_oversight','Human oversight'],['logging_enabled','Technical logging'],['evaluation_plan','Evaluation plan'],['incident_process','Incident process'],['dpia_or_privacy_review','Privacy/DPIA review'],['contract_dpa','DPA / contract evidence'],['subprocessor_inventory','Subprocessor inventory'],['exit_plan','Exit plan'],['ai_disclosure_ready','AI disclosure ready'],['synthetic_content_marking_ready','Synthetic-content marking'],['formal_risk_management_file','Risk-management file'],['legal_classification_review','Legal classification review'],['appeal_process','Appeal / contestability'],['access_control_evidence','Access-control evidence'],['data_minimisation_policy','Data minimisation policy']];

function money(v:number){return new Intl.NumberFormat('en-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v)}
export function CommandCenter(){
 const [active,setActive]=useState('Customer chatbot'); const [form,setForm]=useState<UseCase>(presets[active]); const [result,setResult]=useState<Result|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [history,setHistory]=useState<{name:string;risk:string;readiness:number}[]>([]); const [evaluation,setEvaluation]=useState<{cases:number;risk_band_accuracy:number;decision_accuracy:number}|null>(null);
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem('aigate-history')||'[]'))}catch{setHistory([])};fetch('/api/evaluation').then(r=>r.ok?r.json():null).then(x=>x&&setEvaluation(x)).catch(()=>{})},[]);
 useEffect(()=>{setForm(presets[active]);setResult(null);setError('')},[active]);
 const set=<K extends keyof UseCase>(k:K,v:UseCase[K])=>{setForm(f=>({...f,[k]:v}));setResult(null)};
 async function run(){setBusy(true);setError('');try{const r=await fetch('/api/screen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Screening failed');setResult(data);const next=[{name:form.name,risk:data.risk_band,readiness:data.readiness_score},...history].slice(0,5);setHistory(next);localStorage.setItem('aigate-history',JSON.stringify(next));}catch(e){setError(e instanceof Error?e.message:'Screening failed')}finally{setBusy(false)}}
 function downloadPack(){if(!result)return;const pack={generated_at:new Date().toISOString(),use_case:form,screening:result,scope:'portfolio decision-support; not legal advice'};const blob=new Blob([JSON.stringify(pack,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`aigate-${form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'screening'}.json`;a.click();URL.revokeObjectURL(url)}
 async function copySummary(){if(!result)return;await navigator.clipboard?.writeText(`${form.name} — ${result.risk_band} — ${result.decision} — readiness ${result.readiness_score}/100. ${result.ai_summary}`)}
 const color=useMemo(()=>result?.risk_band==='prohibited-review'?'danger':result?.risk_band==='high-risk-candidate'?'warn':result?.risk_band==='transparency'?'violet':'safe',[result]);
 return <main>
  <div className="ambient a1"/><div className="ambient a2"/>
  <nav className="nav glass"><a href="#top" className="brand">AIGATE<span>EU</span></a><div><a href="#screen">Screen</a><a href="#evidence">Evidence</a><a href="#value">Value</a><a href="#method">Method</a></div><span className="zero">zero-key public mode</span></nav>
  <section id="top" className="hero section"><div className="hero-copy"><p className="eyebrow">AI procurement · governance · value control plane</p><h1>Move AI from request<br/>to governed release.</h1><p className="lede">AIGate turns an AI idea into a traceable decision: risk screening, vendor evidence, control gaps, approval routing and quantified value — with deterministic policy owning the gate.</p><div className="hero-actions"><a className="primary" href="#screen">Run a screening</a><a className="secondary" href="#method">See the control model</a></div><div className="proof"><span>no paid API</span><span>policy-first</span><span>evidence graph</span><span>synthetic portfolio data</span></div></div><EvidenceScene risk={result?.risk_band}/></section>
  <section className="metrics section"><div><b>4</b><span>screening bands</span></div><div><b>{evaluation?.cases??32}</b><span>synthetic evaluation cases</span></div><div><b>{evaluation?`${Math.round(evaluation.decision_accuracy*100)}%`:'100%'}</b><span>decision regression accuracy</span></div><div><b>2</b><span>policy implementations checked for parity</span></div></section>
  <section id="screen" className="section"><div className="section-head"><p className="eyebrow">01 · intake and decisioning</p><h2>Screen the use case before the purchase order.</h2></div><div className="workspace"><aside className="panel glass presets"><h3>Scenario</h3>{Object.keys(presets).map(p=><button className={active===p?'active':''} key={p} onClick={()=>setActive(p)}>{p}</button>)}<hr/><label>Name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Purpose<textarea value={form.purpose} onChange={e=>set('purpose',e.target.value)}/></label><label>Vendor<input value={form.vendor||''} onChange={e=>set('vendor',e.target.value)}/></label><label>Model<input value={form.model||''} onChange={e=>set('model',e.target.value)}/></label></aside><div className="panel glass controls"><h3>Context & controls</h3><div className="toggle-grid">{bools.map(([k,l])=><label className="toggle" key={String(k)}><input type="checkbox" checked={Boolean(form[k]??(['human_oversight','logging_enabled','evaluation_plan'].includes(String(k))))} onChange={e=>set(k,e.target.checked as never)}/><span>{l}</span></label>)}</div><div className="slider-grid"><label>Annual volume <b>{Number(form.annual_volume||0).toLocaleString()}</b><input type="range" min="1000" max="100000" step="1000" value={form.annual_volume||10000} onChange={e=>set('annual_volume',Number(e.target.value))}/></label><label>Minutes saved / case <b>{Math.round(Number(form.hours_saved_per_case||0)*60)}</b><input type="range" min="0" max="0.5" step="0.01" value={form.hours_saved_per_case||.05} onChange={e=>set('hours_saved_per_case',Number(e.target.value))}/></label><label>Implementation € <b>{money(Number(form.implementation_cost_eur||0))}</b><input type="range" min="0" max="120000" step="5000" value={form.implementation_cost_eur||25000} onChange={e=>set('implementation_cost_eur',Number(e.target.value))}/></label></div><button className="run" onClick={run} disabled={busy}>{busy?'Screening…':'Run deterministic screening →'}</button>{error&&<p className="error">{error}</p>}</div></div></section>
  <section id="evidence" className="section result-section"><AnimatePresence mode="wait">{result?<motion.div key={result.decision} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0}} className={`result-grid ${color}`}><div className="result-hero glass"><p className="eyebrow">02 · decision</p><h2>{result.decision.replaceAll('_',' ')}</h2><div className="risk-pill">{result.risk_band}</div><p>{result.ai_summary}</p><div className="result-actions"><button onClick={downloadPack}>Download evidence pack</button><button onClick={copySummary}>Copy decision summary</button></div><small>{result.legal_notice}</small></div><div className="score glass"><span>readiness</span><strong>{result.readiness_score}</strong><div className="meter"><i style={{width:`${result.readiness_score}%`}}/></div><span>evidence {result.evidence_score}% · vendor {result.vendor_score}%</span></div><div className="glass list"><h3>Why</h3>{result.reasons.map(x=><p key={x}>→ {x}</p>)}</div><div className="glass list"><h3>Missing evidence</h3>{(result.missing_controls.length?result.missing_controls:['No critical gaps detected']).slice(0,7).map(x=><p key={x}>○ {x}</p>)}</div><div className="glass route"><h3>Approval route</h3>{result.approval_route.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div><div className="glass list"><h3>Required controls</h3>{result.required_controls.slice(0,8).map(x=><p key={x}>✓ {x}</p>)}</div></motion.div>:<div className="empty glass"><p className="eyebrow">02 · decision</p><h2>Run a scenario to reveal the control path.</h2><p>The result will show classification, decision, control gaps, evidence score, approval route and value case.</p></div>}</AnimatePresence></section>
  <section id="value" className="section"><div className="section-head"><p className="eyebrow">03 · value case</p><h2>Governance without a business case is just paperwork.</h2></div><div className="value-grid">{result?[['Annual benefit',money(result.annual_benefit_eur)],['Annual net value',money(result.annual_net_value_eur)],['First-year ROI',`${result.roi_pct}%`],['Payback',result.payback_months===null?'No payback':`${result.payback_months} months`]].map(([a,b])=><div className="glass" key={a}><span>{a}</span><b>{b}</b></div>):<div className="glass value-placeholder">Value metrics appear after screening.</div>}</div></section>
  <section id="method" className="section method"><div className="section-head"><p className="eyebrow">04 · architecture</p><h2>Reasoning can advise. Policy owns authority.</h2></div><div className="flow"><div>AI request</div><i>→</i><div>deterministic screening</div><i>→</i><div>control gaps</div><i>→</i><div>approval route</div><i>→</i><div>registry & monitoring</div></div><div className="method-grid"><div className="glass"><h3>Deterministic control plane</h3><p>Risk-band screening, approval routing, evidence scoring, vendor scoring and release decisioning are testable policy functions.</p></div><div className="glass"><h3>Optional AI layer</h3><p>A local OpenAI-compatible model may explain evidence or summarize documents, but it cannot change a policy decision or authorize release.</p></div><div className="glass"><h3>Commercial path</h3><p>Community mode stays zero-key. A future SaaS layer can add multi-tenancy, Postgres, SSO, connectors, evidence exports and EU-region operations.</p></div></div></section>
  {history.length>0&&<section className="section"><div className="section-head"><p className="eyebrow">local browser history</p><h2>Recent screenings</h2></div><div className="history">{history.map((h,i)=><div className="glass" key={`${h.name}-${i}`}><b>{h.name}</b><span>{h.risk}</span><strong>{h.readiness}/100</strong></div>)}</div></section>}
  <footer className="section"><b>AIGate</b><span>AI Procurement, Governance & Value Control Plane</span><small>Portfolio-safe decision support · not legal advice</small></footer>
 </main>
}
